index:
    path: /
    controller: App\Controller\LeaderboardController::home

dashboard:
  path: /dashboard
  controller: App\Controller\LeaderboardController::dashboard

login:
  path: /login
  controller: App\Controller\SecurityController::login