index:
    path: /
    controller: App\Controller\LeaderboardController::home

dashboard:
  path: /dashboard
  controller: App\Controller\LeaderboardController::dashboard

forgot_password:
  path: /forgot_password
  controller: App\Controller\SecurityController::forgot_password

login:
  path: /login
  controller: App\Controller\SecurityController::login

logout:
  path: /logout