index:
    path: /
    controller: App\Controller\LeaderboardController::home

leaderboard:
  path: /dashboard
  controller: App\Controller\LeaderboardController::dashboard

login:
  path: /login
  controller: App\Controller\SecurityController::login

admin:
  path: /profile
  controller: App\Controller\ProfileController::index

registration:
  path: /user/register
  controller: App\Controller\RegistrationController::user

place_registration:
  path: /place/register
  controller: App\Controller\RegistrationController::place

deploy:
  path: /deploy
  controller: App\Controller\DeployController::index

logout:
  path: /logout

