index:
    path: /
    controller: App\Controller\LeaderboardController::home

leaderboard:
  path: /dashboard
  controller: App\Controller\LeaderboardController::dashboard

profil:
  path: /profile/{id}
  controller: App\Controller\ProfileController::index
  requirements:
    id: '\d+'

login:
  path: /login
  controller: App\Controller\SecurityController::login

logout:
  path: /logout

